apiVersion: 1
datasources:
  - name: prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    editable: false
    isDefault: true
    jsonData:
      manageAlerts: true
      timeInterval: 30s
  - name: loki
    type: loki
    uid: loki
    access: proxy
    orgId: 1
    url: http://loki:3100
    editable: false
    jsonData:
      manageAlerts: true
      timeInterval: 30s
    secureJsonData:
